### ISSUE TITLE
Parsing AuthorizationResult if authorization is rejected

### ISSUE THREAD

**Issue by milan-b** [DKE-Data/agrirouter-api-dotnet-standard#57]
**Describe the bug**
When parsing AuthorizationResult if authorization is rejected, ArgumentException is thrown. When authorization is rejected, result have only two parameters: "state" and "error", but  AuthorizationService.cs in line 72 checking if there is 3 or 4 parameters - for every other number of parameters ArgumentException is thrown.

**Expected behavior**
I expect that AuthorizationResult is parsed even in case of rejection of authorization.

**Comment by saschadoemer** [comment]
Should be resolved with #58
